services:
  nginx-gateway:
    container_name: nginx-gateway
    build: ./nginx-gateway
    ports:
      - "4443:443"
    volumes:
      - ./nginx-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - certs:/etc/nginx/certs

  # HTTP stub en :3000
  auth-service:
    image: hashicorp/http-echo:1.0
    command: ["-listen", ":3000", "-text", "auth ok"]

  # WebSocket echo stub en :4000 (wss pasa por el gateway, aquí es ws interno)
  game-service:
    image: ealen/echo-server:latest
    environment:
      - PORT=4000
      - ENABLE_WEBSOCKET=true

volumes:
  certs:
